# Alembic Configuration
# This is the Alembic environment configuration file.

[alembic]
# path to migration scripts
scriptLocation = app/migrations

# template system to use when generating migration files
# as of 2.0, this value is recommended to be left as <%! ... %>
sqlalchemy_template_args =
    render_as_batch=True

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
prepend_sys_path = .

# timezone to use when rendering the date
# within the 'create_date' field of a migration file
# string value is passed to dateutil.tz.gettz()
# leave blank for localtime
# timezone =

# max length of characters to apply to the
# "slug" field in an HTTP request.
# set to negative or None to disable
# slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory
# sourceless = false

# logging configuration
# Loggers to configure [default: root]
# keys = root,sqlalchemy.engine

# [logger_root]
# level = WARN
# handlers = console

# [logger_sqlalchemy.engine]
# level = WARN
# handlers =
# qualname = sqlalchemy.engine

# [handler_console]
# class = StreamHandler
# 'format' = %(asctime)s %(levelname)s %(name)s %(message)s
